name: DiaryPaymentsApp
options:
  bundleIdPrefix: com.akiralabs
configs:
  Debug: debug
  Release: release
settings:
  SWIFT_VERSION: 5.0
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
targets:
  DiaryPaymentsApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    coreDataModels:
      - path: Sources/DataModel/DiaryPaymentsApp.xcdatamodeld
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: DiaryPaymentsApp
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UIUserInterfaceStyle: Automatic
        LSRequiresIPhoneOS: true
        NSLocationWhenInUseUsageDescription: "近くの場所や行った場所の記録に位置情報を使用します。"
        NSPhotoLibraryUsageDescription: "日記や支出に写真を添付するために写真ライブラリへアクセスします。"
        NSPhotoLibraryAddUsageDescription: "アプリから撮影した写真をライブラリに保存します。"
        NSCameraUsageDescription: "日記や支出に添付する写真を撮影します。"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akiralabs.DiaryPaymentsApp
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: 1,2
    scheme:
      testTargets: []
      gatherCoverageData: false

